# Generated by Django 3.2.12 on 2022-12-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalapi', '0004_alter_userregistration_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='email',
            field=models.CharField(error_messages={'unique': 'A user with that email already exists.'}, max_length=150, unique=True, verbose_name='email'),
        ),
    ]
