# Generated by Django 3.2.12 on 2023-01-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapi', '0003_projecttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('content', models.CharField(default=None, max_length=20000)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Deleted')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
