# Generated by Django 3.2.12 on 2023-01-07 07:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectapi', '0005_userprojecttemplate_userproposalemplate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProposalemplate',
            new_name='UserProposaltemplate',
        ),
    ]
